apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-deployment
  labels:  
    app: phonebook
spec:  
  replicas: 1
  selector:  
    matchLabels:  
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
      - name: phonebook
        image: phonebook
        ports: 
        - containerPort: 8080
                      
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
spec:
  selector:
    app: phonebook
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080   
      nodePort: 30000
      
